// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.fuchsia:
      case TargetPlatform.linux:
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOMHUeujSQxTPwip7dPY9_lKnC8thuQCY',
    appId: '1:952856895087:web:b6b5e4f1b7401b5271b79a',
    messagingSenderId: '952856895087',
    projectId: 'conecta-itt-55275',
    authDomain: 'conecta-itt-55275.firebaseapp.com',
    storageBucket: 'conecta-itt-55275.firebasestorage.app',
    measurementId: 'G-1PG8F5BMX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7ql_m1krrnR0UqlDElp_VF4RQwW-BN4g',
    appId: '1:952856895087:android:6a66ef3df744610c71b79a',
    messagingSenderId: '952856895087',
    projectId: 'conecta-itt-55275',
    storageBucket: 'conecta-itt-55275.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWhPt9mgbL7JF2MPmT9SCmJYzSMexUd7s',
    appId: '1:952856895087:ios:8afd071c5c11706371b79a',
    messagingSenderId: '952856895087',
    projectId: 'conecta-itt-55275',
    storageBucket: 'conecta-itt-55275.firebasestorage.app',
    iosBundleId: 'com.ituniversity.app',
  );
}
